(()=>{
  'use strict';
  if(window.__MCU_CHRONOLOGY_1618__)return;
  window.__MCU_CHRONOLOGY_1618__=true;

  const VERSION='1.6.19';
  const TELEMETRY_URL='https://svnrfyqloiludzvnylyp.supabase.co/functions/v1/mcu-telemetry';
  const corrected=[
    {t:'Captain America: The First Avenger',w:'Captain America: The First Avenger'},{t:'Captain Marvel',w:'Captain Marvel (film)'},{t:'Iron Man',w:'Iron Man (2008 film)'},{t:'Iron Man 2',w:'Iron Man 2'},{t:'The Incredible Hulk',w:'The Incredible Hulk (film)'},{t:'Thor',w:'Thor (film)'},{t:'The Avengers',w:'The Avengers (2012 film)'},{t:'Thor: The Dark World',w:'Thor: The Dark World'},{t:'Iron Man 3',w:'Iron Man 3'},{t:'Captain America: The Winter Soldier',w:'Captain America: The Winter Soldier'},{t:'Guardians of the Galaxy',w:'Guardians of the Galaxy (film)'},{t:'Guardians of the Galaxy Vol. 2',w:'Guardians of the Galaxy Vol. 2'},{t:'Avengers: Age of Ultron',w:'Avengers: Age of Ultron'},{t:'Ant-Man',w:'Ant-Man (film)'},{t:'Captain America: Civil War',w:'Captain America: Civil War'},{t:'Black Widow',w:'Black Widow (2021 film)'},{t:'Black Panther',w:'Black Panther (film)'},{t:'Spider-Man: Homecoming',w:'Spider-Man: Homecoming'},{t:'Doctor Strange',w:'Doctor Strange (2016 film)'},{t:'Thor: Ragnarok',w:'Thor: Ragnarok'},{t:'Ant-Man and the Wasp',w:'Ant-Man and the Wasp'},{t:'Avengers: Infinity War',w:'Avengers: Infinity War'},{t:'Avengers: Endgame',w:'Avengers: Endgame'},{t:'Shang-Chi and the Legend of the Ten Rings',w:'Shang-Chi and the Legend of the Ten Rings'},{t:'Spider-Man: Far From Home',w:'Spider-Man: Far From Home'},{t:'Eternals',w:'Eternals (film)'},{t:'Spider-Man: No Way Home',w:'Spider-Man: No Way Home'},{t:'Doctor Strange in the Multiverse of Madness',w:'Doctor Strange in the Multiverse of Madness'},{t:'Black Panther: Wakanda Forever',w:'Black Panther: Wakanda Forever'},{t:'Thor: Love and Thunder',w:'Thor: Love and Thunder'},{t:'Ant-Man and the Wasp: Quantumania',w:'Ant-Man and the Wasp: Quantumania'},{t:'Guardians of the Galaxy Vol. 3',w:'Guardians of the Galaxy Vol. 3'},{t:'The Marvels',w:'The Marvels (film)'},{t:'Deadpool & Wolverine',w:'Deadpool & Wolverine'},{t:'Captain America: Brave New World',w:'Captain America: Brave New World'},{t:'Thunderbolts*',w:'Thunderbolts* (film)'},{t:'The Fantastic Four: First Steps',w:'The Fantastic Four: First Steps'},{t:'Spider-Man: Brand New Day',w:'Spider-Man: Brand New Day'}
  ];
  function load(id,file,flag){if(window[flag]||document.getElementById(id))return;const s=document.createElement('script');s.id=id;s.src='https://mcutracker.github.io/app/'+file+'?t='+Date.now();s.async=false;s.onerror=()=>s.remove();document.head.appendChild(s)}
  function patchBlackWidowEntries(){try{const arrays=[];if(typeof ALL_MOVIES!=='undefined'&&Array.isArray(ALL_MOVIES))arrays.push(ALL_MOVIES);if(typeof RELEASE!=='undefined'&&Array.isArray(RELEASE))arrays.push(RELEASE);if(typeof CHRONOLOGICAL!=='undefined'&&Array.isArray(CHRONOLOGICAL))arrays.push(CHRONOLOGICAL);if(typeof DOOMSDAY_DATA!=='undefined'&&Array.isArray(DOOMSDAY_DATA))arrays.push(DOOMSDAY_DATA);arrays.forEach(arr=>arr.forEach(x=>{if(x?.t==='Black Widow')x.w='Black Widow (2021 film)'}))}catch{}}
  function fixBlackWidowPoster(){try{patchBlackWidowEntries();const key='Black Widow (2021 film)';if(typeof posterCache!=='undefined'){delete posterCache['Black Widow'];delete posterCache['Black Widow (film)']}document.querySelectorAll('.poster-logo[data-title="Black Widow"]').forEach(box=>{box.dataset.wiki=key;box.classList.remove('poster-error');box.classList.add('poster-loading');const img=box.querySelector('img');if(img){img.dataset.loaded='';img.removeAttribute('src')}if(typeof setPoster==='function')setPoster(box)})}catch{}}
  function patchFavoriteFilters(){try{document.querySelectorAll('#filterBar button[data-filter]').forEach(btn=>{if(btn.dataset.mcuFilter1618==='1')return;btn.dataset.mcuFilter1618='1';btn.onclick=()=>{try{const mode=btn.dataset.filter||'all';const isFav=mode==='favorites';if(typeof favoriteOnly!=='undefined')favoriteOnly=isFav;if(typeof filter!=='undefined')filter=isFav?'all':mode;document.querySelectorAll('#filterBar button[data-filter]').forEach(x=>x.classList.toggle('active',x===btn));document.getElementById('favFilter')?.classList.toggle('active',isFav);if(typeof renderCurrent==='function')renderCurrent()}catch{}}})}catch{}}
  function applyChronology(){try{if(typeof CHRONOLOGICAL!=='undefined'&&Array.isArray(CHRONOLOGICAL)){CHRONOLOGICAL.splice(0,CHRONOLOGICAL.length,...corrected.map(x=>({...x})));if(typeof DATA!=='undefined'&&DATA)DATA.chronological=CHRONOLOGICAL;if(typeof currentCategory!=='undefined'&&currentCategory==='chronological'&&typeof renderCurrent==='function')renderCurrent(false)}}catch{}}
  function patchVersionUI(){for(const sel of ['.version-pill','[data-current-version]','.profile-rank','.badge'])document.querySelectorAll(sel).forEach(el=>{const text=el.textContent||'';if(/v1\.5\.0|v1\.6\.17|v1\.6\.18/.test(text))el.textContent=text.replace(/v1\.5\.0|v1\.6\.17|v1\.6\.18/g,'v'+VERSION)})}
  function patchTelemetry(){try{if(typeof sendTelemetry==='function')sendTelemetry=function(event){try{fetch(TELEMETRY_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event,version:VERSION}),keepalive:true}).catch(()=>{})}catch{}}}catch{}}
  function apply(){applyChronology();patchBlackWidowEntries();patchFavoriteFilters();patchTelemetry();patchVersionUI();load('mcuDoomsdayOrder1618Loader','doomsday-order-1.6.18.js','__MCU_DOOMSDAY_ORDER_1618__');load('mcuFullChronology1618Loader','full-mcu-chronology-1.6.18.js','__MCU_FULL_CHRONOLOGY_1618__');load('mcuDoomsdayQuickPrep1618Loader','doomsday-quick-prep-1.6.18.js','__MCU_DOOMSDAY_QUICK_PREP_1618__');load('mcuSeriesSync1618Loader','series-sync-1.6.18.js','__MCU_SERIES_SYNC_1618__');load('mcuListStats1618Loader','list-stats-1.6.18.js','__MCU_LIST_STATS_1618__');load('mcuDashboardPlan11618Loader','dashboard-plan1-1.6.18.js','__MCU_DASHBOARD_PLAN1_1618__');load('mcuAdminGrowth1618Loader','admin-growth-stats-1.6.18.js','__MCU_ADMIN_GROWTH_STATS_1618__');load('mcuMenuCleanup1618Loader','menu-cleanup-1.6.18.js','__MCU_MENU_CLEANUP_1618__');load('mcuInstagram1618Loader','instagram-link.js','__MCU_INSTAGRAM_LINK_1618__');load('mcuReleaseNotesFix1618Loader','release-notes-fix-1.6.18.js','__MCU_RELEASE_NOTES_FIX_1618__');load('mcuSeriesRuntime1618Loader','series-runtime-1.6.18.js','__MCU_SERIES_RUNTIME_1618__');load('mcuOnboarding1619Loader','onboarding-1.6.19.js','__MCU_ONBOARDING_1619__')}
  apply();setTimeout(apply,250);setTimeout(()=>{apply();fixBlackWidowPoster()},1000);setTimeout(fixBlackWidowPoster,2500);document.addEventListener('click',()=>setTimeout(()=>{apply();fixBlackWidowPoster()},0),true);window.addEventListener('focus',()=>{apply();fixBlackWidowPoster()},{passive:true});
})();